### ISSUE TITLE
How do you make tissue-specific predictions using DNA sequence?

### ISSUE THREAD

**Issue by fojackson8** [calico/borzoi#4]
Hi, thanks for the great paper. Slightly naive question:

How do you make tissue-specific predictions using DNA sequence, which is identical in each tissue?

I'm trying to understand what the inputs and outputs for model training are. It seems you input is 524kb slices of DNA sequence, and prediction target is RNA-seq coverage (in 32bp bins). The RNA-seq coverage target would be different for each tissue, but the DNA sequence input will be the same. Where does the tissue specific information in the training set come from?

**Comment by johli** [comment]
Hi,

Good question and definitely not naive! As you point out, the input is always the same regardless of the tissue or cell type of interest: a 524,288bp DNA sequence X covering the loci that you're curious about (one-hot coded as 524,288 x 4).

The model works by treating each condition (tissue / cell type / treatment) as a separate and independent output track ("multi-task"). We have 7,611 such output tracks for humans (89 of which correspond to a selection of GTEx tissue samples), so the dimensionality of Borzoi's output Y = Borzoi(X) is 16,384 x 7,611. The first number, 16,384, corresponds to the 32bp coverage bins (i.e. 524,288 / 32). Borzoi has learned during training that the input sequence meant something different in e.g. track 5 (Y[:, 5]) compared to track 142 (Y[:, 142]) due to differences in tissue-specific regulation (perhaps Motif A is not active in track 5 but driving expression in track 142; then the model would learn from training data to predict high coverage density over some gene(s) in Y[:, 142] but low(er) density in Y[:, 5]). With enough training examples, the model learns to generalize these multi-task style predictions to unseen stretches of DNA sequence.

Hopefully this answers your question.

Best,

Johannes

**Comment by akurmustafa** [comment]
I was confused about the same thing while reading the paper. Thanks @johli for the answer and thanks @fojackson8 for asking it. I wonder if there is a documentation what each of the 7611 output indices for human and each of the 2608 output indices for mouse corresponds to? 

Also tangent to this point. I wonder whether during the research, did you consider giving different modes as an input to the model instead of the generating all possible 7611 variants? If so what was the reason behind choosing current approach in the paper.

Best,
