### ISSUE TITLE
Reading TFRecords and extracting sequence information.

### ISSUE THREAD

**Issue by andreaskapou** [calico/borzoi#6]
Hi,

First of all really cool work and thanks for sharing directly the processed data!

On that regard, I am trying to understand how to parse the `tfr` files and extract back the `sequence` and `target` pairs.
I am doing the following:

```python
# Load a single tfr
raw_dataset = tf.data.TFRecordDataset(["fold0-136.tfr"], compression_type="ZLIB")
feature_map = {
    "target": tf.io.FixedLenFeature([], tf.string),
    "sequence": tf.io.FixedLenFeature([], tf.string),
}

for raw_record in raw_dataset.take(1):
    parsed_record = tf.io.parse_example(raw_record, feature_map)
    sequence = tf.io.decode_raw(parsed_record["sequence"], tf.bool)
    sequence_reshaped = tf.reshape(sequence, (-1, 4))
```

Now when I print the decoded sequence I get (where the size matches the `seq_length` defined in the `statistics.json` file):
```python
print(sequence)
>> tf.Tensor([ True  True False ...  True  True  True], shape=(524288,), dtype=bool)
```

Now when I print the reshaped sequence to match what I would think the one-hot-encoding (OHE) of DNA sequence, I get
```python
print(sequence_reshaped.shape)
>> (131072, 4)
```

and then when I print the reshaped sequence I actually do not get OHE rows for the DNA sequence.
```
print(sequence_reshaped
>> tf.Tensor(
[[ True  True False  True]
 [ True False  True  True]
 [ True False  True False]
 ...
 [ True False  True  True]
 [False  True  True  True]
 [ True  True  True  True]], shape=(131072, 4), dtype=bool)
```

So am I doing something wrong during the loading/transformation of the `TFRecords` that I am not getting back a OHE DNA sequence of `(524288, 4)` shape?

Thank you in advance!

**Comment by houruiyan** [comment]
Hi , 

I think the problem is that you assigned a wrong data type. For the sequence, the data type should be tf.uint8 rather than  bool. Then the output should be the number range from 0 to 4. 

You can refer this code https://github.com/calico/basenji/blob/master/basenji/dataset.py#L87 

In addition, I am a newbie for the tensorflow and the borizo. I found their package basenji, enformer and borizo are all based a lot of function in the basenji. I want to do the fine tuning. But it is very hard and pain for my to parse their code and run them in tensorflow. A lot of object are basenji object. If you are doing the same thing, we can communicate more.  

Best regards,
Ruiyan

**Comment by andreaskapou** [comment]
Thank you very much for the reply Ruiyan! 

Defining type as `uint8` indeed extract the sequence information. I am just starting with this and I wanted to understand better their input data and I mostly have pytorch background. 

Best,
Andreas
